### ISSUE TITLE
AWS schedules are not getting called

### ISSUE THREAD

**Issue by asalkeld** [nitrictech/cli#195]
**Describe the bug**
AWS schedules seem to have stopped working.

**To Reproduce**

The following should pass
```
clone github.com/asalkeld/test-app
nitric up -s aws
# get the api url
export BASE_URL=<from above>
make test
```
the test case TestAppQueue fails.

**Output of `nitric info -o yaml`:**

```yaml
os: linux
arch: amd64
goversion: go1.17.7
cliversion: v1.1.0-develop.14-97-gd1f4bf27fbfae045f0af330ac83883463f8dfcc1
fabricversion: v0.15.1-rc.7
containerruntime: docker
containerruntimeversion: |
  platform:
    name: Docker Engine - Community
  components:
  - name: Engine
    version: 20.10.13
    details:
      ApiVersion: "1.41"
      Arch: amd64
      BuildTime: "2022-03-10T14:06:06.000000000+00:00"
      Experimental: "false"
      GitCommit: 906f57f
      GoVersion: go1.16.15
      KernelVersion: 5.16.14-200.fc35.x86_64
      MinAPIVersion: "1.12"
      Os: linux
  - name: containerd
    version: 1.5.10
    details:
      GitCommit: 2a1d4dbdb2a1030dc5b01e96fb110a9d9f150ecc
  - name: runc
    version: 1.0.3
    details:
      GitCommit: v1.0.3-0-gf46b6ba
  - name: docker-init
    version: 0.19.0
    details:
      GitCommit: de40ad0
  version: 20.10.13
  apiversion: "1.41"
  minapiversion: "1.12"
  gitcommit: 906f57f
  goversion: go1.16.15
  os: linux
  arch: amd64
  kernelversion: 5.16.14-200.fc35.x86_64
  experimental: false
  buildtime: "2022-03-10T14:06:06.000000000+00:00"
```
