### ISSUE TITLE
Design: Dockerfile Support

### ISSUE THREAD

**Issue by tjholm** [nitrictech/cli#447]
Support deployment of a target dockerfile within a nitric project.

This will need to include considerations for:

- [ ] Skipping membrane wrapping (useful for single purpose/utility software)
- [ ] Setting build context
- [ ] Setting additional build arguments
- [ ] Setting environment variables
- [ ] Local run environment variables

Acceptance Critera:

- [ ] A design proposal that includes the ability to add a dockerfile as part of a nitric project file as a function (service).

**Comment by tjholm** [comment]
The overall support for this is quite simple, as the CLI already builds docker images as part of the deployment process, the configuration at the moment has some compatability issues.

```yaml
name: my-nitric-project
handlers:
  - "functions/*.ts"
```

Currently we deploy with a simple string for scripts/program targets, but for dockerfiles the number of configurable properties gets a bit more complex.

```yaml
name: my-nitric-project
handlers:
 # Auto detect runtime for simple functions who's dependencies are purely within their languages native dependency system
 - "functions/*.ts"
# Object based definition for dockerfiles
 - dockerfile: docker/my-service.dockerfile
   # Need to be able to give a unique name (we may not be able to infer from the dockerfile as it could be re-used for multiple services
   name: my-function-name
   # Need configurable build context
   context: .
   # Needs configurable builds args
   args:
      MY_BUILD_ARG: SOME_VALUE
   # Need a way to instruct that this artifact may/may not be wrapped prior to deployment
   # Providers are responsible for wrapping, so depending on the runtime target it will also need to implement any special requirements
   nitric: false
```

**Comment by davemooreuws** [comment]
Great example @tjholm !

The only potential changes I would make are moving the docker objects into its own key outside of handlers (maybe dockerHandlers). The reasons for this would be helping parse and validate the yaml in the CLI and separate the concerns of the auto generated handlers.

**Comment by tjholm** [comment]
from discussion:

 - Move containers defintions into a separate `containers` key.
 
 ```yaml
 name: my-nitric-project
handlers:
 # Auto detect runtime for simple functions who's dependencies are purely within their languages native dependency system
 - "functions/*.ts"
containers:
# Object based definition for dockerfiles
 - image: my-locally-built-image # as a URI reference
 - dockerfile: docker/*.dockerfile #required!: glob location of dockerfiles to build
   # Need to be able to give a unique name (we may not be able to infer from the dockerfile as it could be re-used for multiple services
   # Use docker LABEL for naming e.g. LABEL io.nitric.name=my-service-name
   # Need configurable build context
   # context: . #optional: defaults to workdir of glob matched dockerfile
   # Needs configurable builds args
   args:
      TURBO_REPO_SCOPE: "@mah-pkg/all-my-functions"
   # Need a way to instruct that this artifact may/may not be wrapped prior to deployment
   # Providers are responsible for wrapping, so depending on the runtime target it will also need to implement any special requirements
   nitric: false
 ```

**Comment by tjholm** [comment]
Draft from discussion

project yaml file syntaxt

```yaml
name: string
handlers: []string

containers: [](Dockerfile | Image)
```

Dockerfile object syntax
```yaml
dockerfile: string
args: map<string, string>
context: string
nitric: boolean
```

Image object syntax
```yaml
image: string
nitric: boolean
```
