### ISSUE TITLE
Improve support for monorepos with docker context config

### ISSUE THREAD

**Issue by davemooreuws** [nitrictech/cli#744]
### Suggestion
At the moment the docker context is wherever the nitric project is located. A solution to this would be to add a new key to the custom runtimes config called `context`

### Value
Ability to include all the files for a monorepo, to allow it to be installed and built and share packages.

### Alternatives
Moving projects to the root. Which isn't ideal.

## Example for turbo repo

```yaml
name: guestbook-api
services:
  - match: services/*.ts
    runtime: turbo
    type: ""
    start: npm run dev:services $SERVICE_PATH
runtimes:
  turbo:
    # All services that specify the 'turbo' runtime will be built using this dockerfile
    dockerfile: ./turbo.dockerfile
    context: ../../
    args:
      TURBO_SCOPE: "guestbook-api"
```
