### ISSUE TITLE
GitLab pipelines issue running nitric up on shared runners

### ISSUE THREAD

**Issue by davemooreuws** [nitrictech/cli#769]
### Issue

On GitLab pipelines, with shared runners there are issues connecting to the containers.

### Steps

With latest docker (27~) there are connection errors.

```yaml
deploy:
  image: docker:latest
  services:
    - docker:dind
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  variables:
    PULUMI_CONFIG_PASSPHRASE: $PULUMI_ACCESS_TOKEN
    PULUMI_ACCESS_TOKEN: $PULUMI_ACCESS_TOKEN
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

  before_script:
    - apk update && apk add --no-cache curl bash
    - curl -L https://nitric.io/install?version=latest | bash
    - export PATH=$PATH:$HOME/.nitric/bin
    - curl -fsSL https://get.pulumi.com/ | bash
    - export PATH=$PATH:$HOME/.pulumi/bin
  script:
    - nitric up --ci
```

With docker in docker recommended version docker (24~) there are resources that are not deployed. (i.e. API gateway)

```yaml
deploy:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  variables:
    PULUMI_CONFIG_PASSPHRASE: $PULUMI_ACCESS_TOKEN
    PULUMI_ACCESS_TOKEN: $PULUMI_ACCESS_TOKEN
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

  before_script:
    - apk update && apk add --no-cache curl bash
    - curl -L https://nitric.io/install?version=latest | bash
    - export PATH=$PATH:$HOME/.nitric/bin
    - curl -fsSL https://get.pulumi.com/ | bash
    - export PATH=$PATH:$HOME/.pulumi/bin
  script:
    - nitric up --ci
```

I have also tried adding these variables, which do not fix any of the above:

```
DOCKER_HOST: tcp://docker:2375
DOCKER_DRIVER: overlay2
DOCKER_TLS_CERTDIR: ""
```

### Expected

It should work.

### Environment and setup information

- Nitric CLI Version: v1.50.2
- Operating System:
- Nitric dependencies and their versions, such as SDKs or Middleware: Python SDK
- Cloud providers you are deploying to and their version: nitric/aws@1.11.6

### Other info
Errors with latest docker:
![image](https://github.com/user-attachments/assets/58da1f2a-425e-4feb-9c66-30ae73c20399)

False success with docker 24 (missing API gateway output/deployment):
![image](https://github.com/user-attachments/assets/c514e1c0-0570-4412-be3c-15ffc391b0ca)
